# Generated by Django 5.0.4 on 2024-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_discipline_image_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ebillet_path',
            field=models.FileField(blank=True, null=True, upload_to='ebillets/'),
        ),
    ]
