# Generated by Django 5.0.4 on 2024-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Evenement',
            new_name='evenement',
        ),
    ]
