# Generated by Django 5.0.4 on 2024-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sport_images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
