# Generated by Django 5.0.4 on 2024-09-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_cle_securite_commande_cle_securite_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
