# Generated by Django 5.0.4 on 2024-09-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_evenement_commande_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='formule',
        ),
        migrations.AddField(
            model_name='commande',
            name='evenements',
            field=models.ManyToManyField(to='shop.evenement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='formules',
            field=models.ManyToManyField(to='shop.formule'),
        ),
    ]
