# Generated by Django 5.0.4 on 2024-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Discipline',
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_event', models.DateTimeField()),
                ('image', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Discipline', to='shop.discipline')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('evet_rattache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EV', to='shop.evenement')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
