# Generated by Django 5.0.4 on 2024-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_category_discipline_evenement_formule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
