# Generated by Django 5.0.4 on 2024-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_commande_evenement_remove_commande_formule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='evenements',
            field=models.ManyToManyField(related_name='commandes', to='shop.evenement'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='formules',
            field=models.ManyToManyField(related_name='commandes', to='shop.formule'),
        ),
    ]
