# Generated by Django 5.0.4 on 2024-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_evenement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='price',
            new_name='price_multiplier',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='evet_rattache',
        ),
        migrations.AddField(
            model_name='evenement',
            name='base_price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='formules',
            field=models.ManyToManyField(related_name='formule_choisie', to='shop.formule'),
        ),
    ]
