# Generated by Django 5.0.4 on 2024-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commande_evenements_alter_commande_formules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='evenements',
            field=models.ManyToManyField(related_name='commandes_evenements', to='shop.evenement'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='formules',
            field=models.ManyToManyField(related_name='commandes_formules', to='shop.formule'),
        ),
    ]
