# Generated by Django 5.0.4 on 2024-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_utilisateur_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ebillet_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
