# Generated by Django 5.0.4 on 2024-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_commande_evenements_alter_commande_formules'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
