# Generated by Django 5.0.4 on 2024-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commande_ebillet_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='commande',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
