# Generated by Django 5.0.4 on 2024-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default='inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='courriel',
            field=models.EmailField(default='inconnu', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='inconnu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default='inconnu', max_length=50),
            preserve_default=False,
        ),
    ]
