# Generated by Django 5.0.4 on 2024-09-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_commande_options_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
