# Generated by Django 5.0.4 on 2024-09-04 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_utilisateur_adresse_utilisateur_courriel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='courriel',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='cle_securite',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
